# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &hospital
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: hospitalMSP

        # ID to load the MSP definition as
        ID: hospitalMSP

        MSPDir: ../organizations/peerOrganizations/hospital.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('hospitalMSP.admin', 'hospitalMSP.peer', 'hospitalMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('hospitalMSP.admin', 'hospitalMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('hospitalMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('hospitalMSP.peer')"
