#!/bin/bash

function createOrg1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/bloodcollection.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/bloodcollection.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-bloodcollection --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bloodcollection.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bloodcollection.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bloodcollection.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-bloodcollection.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy bloodcollection's CA cert to bloodcollection's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/msp/tlscacerts/ca.crt"

  # Copy bloodcollection's CA cert to bloodcollection's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/tlsca/tlsca.bloodcollection.example.com-cert.pem"

  # Copy bloodcollection's CA cert to bloodcollection's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/ca/ca.bloodcollection.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-bloodcollection --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-bloodcollection --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-bloodcollection --id.name bloodcollectionadmin --id.secret bloodcollectionadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-bloodcollection -M "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-bloodcollection -M "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls" --enrollment.profile tls --csr.hosts peer0.bloodcollection.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/peers/peer0.bloodcollection.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-bloodcollection -M "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/users/User1@bloodcollection.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/users/User1@bloodcollection.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://bloodcollectionadmin:bloodcollectionadminpw@localhost:7054 --caname ca-bloodcollection -M "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/users/Admin@bloodcollection.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodcollection/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodcollection.example.com/users/Admin@bloodcollection.example.com/msp/config.yaml"
}

function createOrg2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/bloodprocessing.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-bloodprocessing --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodprocessing.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodprocessing.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodprocessing.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodprocessing.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy bloodprocessing's CA cert to bloodprocessing's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/msp/tlscacerts/ca.crt"

  # Copy bloodprocessing's CA cert to bloodprocessing's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/tlsca/tlsca.bloodprocessing.example.com-cert.pem"

  # Copy bloodprocessing's CA cert to bloodprocessing's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/ca/ca.bloodprocessing.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-bloodprocessing --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-bloodprocessing --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-bloodprocessing --id.name bloodbankadmin --id.secret bloodbankadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-bloodprocessing -M "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-bloodprocessing -M "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls" --enrollment.profile tls --csr.hosts peer0.bloodprocessing.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/peers/peer0.bloodprocessing.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-bloodprocessing -M "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/users/User1@bloodprocessing.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/users/User1@bloodprocessing.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://bloodbankadmin:bloodbankadminpw@localhost:8054 --caname ca-bloodprocessing -M "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/users/Admin@bloodprocessing.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodprocessing/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodprocessing.example.com/users/Admin@bloodprocessing.example.com/msp/config.yaml"
}

function createOrg3() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/bloodbank.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/bloodbank.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-bloodbank --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodbank.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodbank.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodbank.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-bloodbank.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/bloodbank.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy bloodbank's CA cert to bloodbank's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodbank.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodbank.example.com/msp/tlscacerts/ca.crt"

  # Copy bloodbank's CA cert to bloodbank's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodbank.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodbank.example.com/tlsca/tlsca.bloodbank.example.com-cert.pem"

  # Copy bloodbank's CA cert to bloodbank's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/bloodbank.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/bloodbank.example.com/ca/ca.bloodbank.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-bloodbank --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-bloodbank --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-bloodbank --id.name bloodbankadmin --id.secret bloodbankadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-bloodbank -M "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodbank.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-bloodbank -M "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls" --enrollment.profile tls --csr.hosts peer0.bloodbank.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/bloodbank.example.com/peers/peer0.bloodbank.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-bloodbank -M "${PWD}/organizations/peerOrganizations/bloodbank.example.com/users/User1@bloodbank.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodbank.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodbank.example.com/users/User1@bloodbank.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://bloodbankadmin:bloodbankadminpw@localhost:8054 --caname ca-bloodbank -M "${PWD}/organizations/peerOrganizations/bloodbank.example.com/users/Admin@bloodbank.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/bloodbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/bloodbank.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/bloodbank.example.com/users/Admin@bloodbank.example.com/msp/config.yaml"
}

function createOrg4() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hospitals.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hospitals.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-hospitals --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hospitals.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hospitals.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hospitals.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-hospitals.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hospitals.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hospitals's CA cert to hospitals's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospitals.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospitals.example.com/msp/tlscacerts/ca.crt"

  # Copy hospitals's CA cert to hospitals's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospitals.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospitals.example.com/tlsca/tlsca.hospitals.example.com-cert.pem"

  # Copy hospitals's CA cert to hospitals's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospitals.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospitals.example.com/ca/ca.hospitals.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hospitals --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-hospitals --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hospitals --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospitals.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls" --enrollment.profile tls --csr.hosts peer0.hospitals.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hospitals.example.com/peers/peer0.hospitals.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.example.com/users/User1@hospitals.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospitals.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospitals.example.com/users/User1@hospitals.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:8054 --caname ca-hospitals -M "${PWD}/organizations/peerOrganizations/hospitals.example.com/users/Admin@hospitals.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospitals/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospitals.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospitals.example.com/users/Admin@hospitals.example.com/msp/config.yaml"
}

function createOrg5() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/transportation.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/transportation.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-transportation --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-transportation.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-transportation.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-transportation.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-transportation.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy transportation's CA cert to transportation's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/tlscacerts/ca.crt"

  # Copy transportation's CA cert to transportation's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/transportation.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/transportation.example.com/tlsca/tlsca.transportation.example.com-cert.pem"

  # Copy transportation's CA cert to transportation's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/transportation.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/transportation.example.com/ca/ca.transportation.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls" --enrollment.profile tls --csr.hosts peer0.transportation.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/users/User1@transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/users/User1@transportation.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:8054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/users/Admin@transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/users/Admin@transportation.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
