#!/bin/bash

function createOrg1() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hospital.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hospital.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:12054 --caname ca-hospital --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-hospital.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-hospital.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-hospital.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-hospital.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/tlscacerts/ca.crt"

  # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.example.com/tlsca/tlsca.hospital.example.com-cert.pem"

  # Copy org1's CA cert to org1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.example.com/ca/ca.hospital.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name hospitaladmin --id.secret hospitaladminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls" --enrollment.profile tls --csr.hosts peer0.hospital.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/tls/server.key"

infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:12054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/msp/config.yaml"

  infoln "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:12054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls" --enrollment.profile tls --csr.hosts peer1.hospital.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:12054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.example.com/users/User1@hospital.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.example.com/users/User1@hospital.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://hospitaladmin:hospitaladminpw@localhost:12054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.example.com/users/Admin@hospital.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.example.com/users/Admin@hospital.example.com/msp/config.yaml"
}

function createOrg2() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/transportation.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/transportation.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:13054 --caname ca-transportation --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-13054-ca-transportation.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-13054-ca-ortransportationg2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-13054-ca-transportation.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-13054-ca-transportation.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy transportation's CA cert to transportation's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/tlscacerts/ca.crt"

  # Copy transportation's CA cert to transportation's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/transportation.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/transportation.example.com/tlsca/tlsca.transportation.example.com-cert.pem"

  # Copy transportation's CA cert to transportation's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/transportation.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem" "${PWD}/organizations/peerOrganizations/transportation.example.com/ca/ca.transportation.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-transportation --id.name transportationadmin --id.secret transportationadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:13054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:13054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls" --enrollment.profile tls --csr.hosts peer0.transportation.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer0.transportation.example.com/tls/server.key"

infoln "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:12054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/msp/config.yaml"

  infoln "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:12054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls" --enrollment.profile tls --csr.hosts peer1.transportation.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/transportation.example.com/peers/peer1.transportation.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:13054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/users/User1@transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/users/User1@transportation.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://transportationadmin:transportationadminpw@localhost:13054 --caname ca-transportation -M "${PWD}/organizations/peerOrganizations/transportation.example.com/users/Admin@transportation.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/transportation/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/transportation.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/transportation.example.com/users/Admin@transportation.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:14054 --caname ca-orderer2 --tls.certfiles "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-14054-ca-orderer2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-14054-ca-orderer2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-14054-ca-orderer2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-14054-ca-orderer2.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer2 --id.name orderer2 --id.secret orderer2pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer2 --id.name orderer2Admin --id.secret orderer2Adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer2:orderer2pw@localhost:14054 --caname ca-orderer2 -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer2:orderer2pw@localhost:14054 --caname ca-orderer2 -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls" --enrollment.profile tls --csr.hosts orderer2.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://orderer2Admin:orderer2Adminpw@localhost:14054 --caname ca-orderer2 -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orderer2Org/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
