# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &bloodbank
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: bloodbankMSP

        # ID to load the MSP definition as
        ID: bloodbankMSP

        MSPDir: ../organizations/peerOrganizations/bloodbank.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('bloodbankMSP.admin', 'bloodbankMSP.peer', 'bloodbankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('bloodbankMSP.admin', 'bloodbankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('bloodbankMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('bloodbankMSP.peer')"
